# Generated by Django 4.2.7 on 2023-12-16 09:37

from django.db import migrations, models
import product_app.custom


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default=None, storage=product_app.custom.FirebaseStorage(), upload_to='products'),
        ),
    ]
